<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'prestashop');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
define('_DB_PREFIX_', 'ps_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'EW8K9siJq0OE37JtdOdKLd4WJInXKToaNfGbO3zmVytM0ov7IGNHiHZL');
define('_COOKIE_IV_', 'ebL5gdHz');
define('_PS_CREATION_DATE_', '2014-07-10');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.8');
define('_RIJNDAEL_KEY_', 'o3vWBJWHYkVAsO4D4PJ5L0PBw2XArXen');
define('_RIJNDAEL_IV_', 'rBgWDOMfgb3tTAJqsCpBWg==');
